# Pandas Basics: Data Analysis Toolkit

**Duration:** 3 Hours  
**Format:** Interactive Zoom Session

## 📋 Pre-Class Setup
Please run the cell below to ensure your environment is ready. We will use `numpy` and `pandas` throughout this lesson.

In [1]:
import pandas as pd
import numpy as np

print("Pandas version:", pd.__version__)
print("Numpy version:", np.__version__)

Pandas version: 1.5.3
Numpy version: 1.26.4

---

## 🎯 Section 1: Creating & Modifying Data Structures (60 min)

### Learning Objectives (LO1)
By the end of this section, you will be able to:
- **Create** Series and DataFrames from raw data.
- **Modify** DataFrames by adding new columns and changing values.
- **Identify** the index and column components.
- **Detect** missing values using `isna()` and `notna()`.

### 📖 Concept: The Series
A Series is a one-dimensional array with labeled indices. It's the building block of a DataFrame.

In [2]:
# [DEMO] Creating a Series
obj = pd.Series([4, 7, -5, 3], index=["d", "b", "a", "c"])
obj

d    4
b    7
a   -5
c    3
dtype: int64

In [3]:
pd.Series([24,343,"text"])

0      24
1     343
2    text
dtype: object

### 📖 Concept: The DataFrame
A DataFrame is a 2-dimensional labeled data structure. Think of it as a dictionary of Series objects (each column is a Series).

In [4]:
# [DEMO] Creating a DataFrame from a dictionary
data = {
    "state": ["Ohio", "Ohio", "Ohio", "Nevada", "Nevada", "Nevada"],
    "year": [2000, 2001, 2002, 2001, 2002, 2003],
    "pop": [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]
}

frame = pd.DataFrame(data)
frame

    state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [5]:
frame.head(2)

  state  year  pop
0  Ohio  2000  1.5
1  Ohio  2001  1.7

### 👨‍🏫 Instructor Demo: Inspecting & Modifying
1. `head()` and `tail()`
2. Accessing columns (dictionary syntax vs dot syntax)
3. Adding a new column

In [6]:
# [DEMO] Inspecting data
print("First 5 rows:")
display(frame.head())

# [DEMO] Accessing a column
print("Population column:")
display(frame['pop'])

First 5 rows:

    state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

Population column:

0    1.5
1    1.7
2    3.6
3    2.4
4    2.9
5    3.2
Name: pop, dtype: float64

In [7]:
frame.describe()

              year       pop
count     6.000000  6.000000
mean   2001.500000  2.550000
std       1.048809  0.836062
min    2000.000000  1.500000
25%    2001.000000  1.875000
50%    2001.500000  2.650000
75%    2002.000000  3.125000
max    2003.000000  3.600000

In [8]:
# [DEMO] Adding a new column with a scalar value
frame['debt'] = 16.5
print(frame)
frame #In an interactive environment, the cell automatically displays the value of the very last line of code, 
      #provided that line returns an object.

    state  year  pop  debt
0    Ohio  2000  1.5  16.5
1    Ohio  2001  1.7  16.5
2    Ohio  2002  3.6  16.5
3  Nevada  2001  2.4  16.5
4  Nevada  2002  2.9  16.5
5  Nevada  2003  3.2  16.5

    state  year  pop  debt
0    Ohio  2000  1.5  16.5
1    Ohio  2001  1.7  16.5
2    Ohio  2002  3.6  16.5
3  Nevada  2001  2.4  16.5
4  Nevada  2002  2.9  16.5
5  Nevada  2003  3.2  16.5

In [9]:
# [DEMO] Adding a calculated column
frame['eastern'] = frame.state == 'Ohio'
frame #can use frame['state'] == 'Ohio'

    state  year  pop  debt  eastern
0    Ohio  2000  1.5  16.5     True
1    Ohio  2001  1.7  16.5     True
2    Ohio  2002  3.6  16.5     True
3  Nevada  2001  2.4  16.5    False
4  Nevada  2002  2.9  16.5    False
5  Nevada  2003  3.2  16.5    False

### 📖 Concept: Detecting Missing Data
Real-world data often has missing values (shown as `NaN`). Use `isna()` and `notna()` to detect them.

In [10]:
# [DEMO] Detecting missing values
data_with_nan = pd.Series([1, np.nan, 3.5, np.nan, 7])

print("Original data:")
display(data_with_nan)

print("\nWhich values are missing?")
display(data_with_nan.isna())

print("\nWhich values are NOT missing?")
display(data_with_nan.notna())

Original data:

0    1.0
1    NaN
2    3.5
3    NaN
4    7.0
dtype: float64

Which values are missing?

0    False
1     True
2    False
3     True
4    False
dtype: bool

Which values are NOT missing?

0     True
1    False
2     True
3    False
4     True
dtype: bool

### ✏️ Hands-On Activity: The Inventory System

**Scenario:** You manage a small grocery store. You need to track your fruit inventory.

**Tasks:**
1. Create a DataFrame named `inventory` from the provided dictionary `fruit_data`.
2. Add a new column `price` with values `[3.0, 4.0, 2.0, 5.0]`.
3. Add a column `total_value` which is `quantity * price`.
4. Create a boolean column `low_stock` that is `True` if quantity is less than 50.

# [EXERCISE] Starter Code

fruit_data = {

    "fruit": ["Apple", "Banana", "Cherry", "Date"],

    "quantity": [100, 40, 200, 20]

}

# 1. Create DataFrame

# inventory = ...

import pandas as pd

inventory = pd.DataFrame(fruit_data)

inventory

# 2. Add Price

inventory["price"] = [3.0, 4.0, 2.0, 5.0]

inventory

# 3. Calculate Total Value

inventory["total_value"] = inventory["quantity"] * inventory["price"]

inventory

# 4. Flag Low Stock

inventory["low_stock"] = inventory["quantity"] < 50

inventory

# Display result

In [11]:
# [EXERCISE] Starter Code
fruit_data = {
    "fruit": ["Apple", "Banana", "Cherry", "Date"],
    "quantity": [100, 40, 200, 20]
}

# 1. Create DataFrame
inventory = pd.DataFrame(fruit_data)

# 2. Add Price
inventory['price'] = [3.0, 4.0, 2.0, 5.0]

# 3. Calculate Total Value
inventory['total_value'] = inventory['quantity']*inventory['price']

# 4. Flag Low Stock
inventory['low_stock'] = inventory['quantity'] < 50
# Display result

display(inventory)
inventory

    fruit  quantity  price  total_value  low_stock
0   Apple       100    3.0        300.0      False
1  Banana        40    4.0        160.0       True
2  Cherry       200    2.0        400.0      False
3    Date        20    5.0        100.0       True

    fruit  quantity  price  total_value  low_stock
0   Apple       100    3.0        300.0      False
1  Banana        40    4.0        160.0       True
2  Cherry       200    2.0        400.0      False
3    Date        20    5.0        100.0       True

---

## 🎯 Section 2: Indexing and Selection (60 min)

### Learning Objectives (LO2)
By the end of this section, you will be able to:
- **Differentiate** between label-based (`loc`) and position-based (`iloc`) indexing.
- **Apply** boolean filtering to select specific rows.
- **Drop** rows or columns from a DataFrame.
- **Modify** specific data points using selection.

In [12]:
# Setup for Demo
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                    index=["Ohio", "Colorado", "Utah", "New York"],
                    columns=["one", "two", "three", "four"])
data

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [13]:
data.loc["Colorado"]

one      4
two      5
three    6
four     7
Name: Colorado, dtype: int64

### 👨‍🏫 Instructor Demo: Loc vs Iloc
- **.loc[row_label, col_label]**: "Address" based.
- **.iloc[row_pos, col_pos]**: "GPS" based (integers).

In [14]:
# [DEMO] Select 'Colorado' row using loc
print("--- Row by Label ---")
display(data.loc["Colorado"])

# [DEMO] Select 'Colorado' row using iloc (it's at index 1)
print("\n--- Row by Position ---")
display(data.iloc[1,1])

--- Row by Label ---

one      4
two      5
three    6
four     7
Name: Colorado, dtype: int64

--- Row by Position ---

5

In [15]:
# [DEMO] Boolean Filtering
# Select rows where column 'three' is greater than 5
data[data["three"] > 5]

          one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

### 📖 Concept: Dropping Rows and Columns
Use the `drop()` method to remove rows or columns. By default, it drops rows. Use `axis=1` or `axis="columns"` to drop columns.

In [16]:
# [DEMO] Dropping rows and columns
print("Drop rows 'Colorado' and 'Ohio':")
display(data.drop(["Colorado", "Ohio"]))

print("\nDrop column 'two':")
display(data.drop("two", axis=1))

Drop rows 'Colorado' and 'Ohio':

          one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

Drop column 'two':

          one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

The drop will not change the original data base.
use "inplace = true" to replace the data. But a good practise to use it

Another way yo drop a column is to select the colummn you want. eg data = data[["one", "three", "four"]]

### ✏️ Hands-On Activity: Data Detective

**Tasks:**
Using the `data` DataFrame provided above:
1. Select the rows for 'Utah' and 'New York' only.
2. Select the value in the 'two' column for 'Ohio' (should be 1).
3. Select all rows where column 'three' is greater than 5.
4. Update the value of 'four' in the 'New York' row to be 100.

# 1. Utah and New York

data.loc[data.index.isin(["Utah", "New York"])]



# 2. 'two' for 'Ohio'

data.loc["Ohio", "two"]



# 3. Filter > 5

data[data["three"] > 5]

# 4. Update value

data.loc["New York", "four"] = 100

# [EXERCISE] Write your code here

data = pd.DataFrame(np.arange(16).reshape((4, 4)),

                    index=["Ohio", "Colorado", "Utah", "New York"],

                    columns=["one", "two", "three", "four"])

data

# 1. Utah and New York

utah_ny = data.loc[['Utah', 'New York']]

print(f"\n #1 The data frame for Utah and New York :")

display(utah_ny)

# 2. 'two' for 'Ohio'

ohio_two = data.loc['Ohio', 'two']

print(f"\n #2 The value for Ohio in column 'two' is: {ohio_two}")

# 3. Filter > 5

greater_than_five = data[data['three'] > 5]

print(f"\n #3 All rows where column 'three' is greater than 5 : ")

display(greater_than_five)

# 4. Update value

data.loc['New York', 'four'] = 100

print(f"\n #4 Updating the value of 'four' in the 'New York' row to be 100")

display(data)

In [28]:
# [EXERCISE] Write your code here

# Setup for Demo
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                    index=["Ohio", "Colorado", "Utah", "New York"],
                    columns=["one", "two", "three", "four"])

# 1. Utah and New York
display(data.loc[['Utah','New York']])
# 2. 'two' for 'Ohio'
display(data.loc['Ohio', 'two'])
#print(data.loc["Ohio", "two"])
# 3. Filter column 'three'> 5
display(data.loc[data['Three']>5])

# 4. Update value of 'four' in the 'New York' row to be 100
data.loc['New York', 'four'] = 100
data

          one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

1

KeyError: 'Three'

---

## 🎯 Section 3: Function Application, Sorting, & Ranking (60 min)

### Learning Objectives (LO3 & LO4)
By the end of this section, you will be able to:
- **Sort** data by index or values.
- **Rank** data to handle ties.
- **Apply** custom functions to transform data.

In [18]:
# Setup Data
frame = pd.DataFrame({
    "b": [4, 7, -3, 2],
    "a": [0, 1, 0, 1]
}, index=['Row1', 'Row2', 'Row3', 'Row4'])
frame

      b  a
Row1  4  0
Row2  7  1
Row3 -3  0
Row4  2  1

### 👨‍🏫 Instructor Demo: Sorting & Ranking
1. `sort_index()`
2. `sort_values(by=...)`
3. `rank()`

In [19]:
# [DEMO] Sort by values in column 'b'
frame.sort_values(by="b")

      b  a
Row3 -3  0
Row4  2  1
Row1  4  0
Row2  7  1

In [20]:
# [DEMO] Applying a function
def label_size(val):
    return "Big" if val > 2 else "Small"

frame['b_size'] = frame['b'].apply(label_size)
frame

      b  a b_size
Row1  4  0    Big
Row2  7  1    Big
Row3 -3  0  Small
Row4  2  1  Small

### ✏️ Hands-On Activity: Leaderboard Logic

**Scenario:** You have exam scores. You need to rank them and assign a Pass/Fail status.

**Tasks:**
1. Run the starter code to generate the `scores` DataFrame.
2. Sort the DataFrame by 'Math' score in descending order (highest first).
3. Create a new column 'Math_Rank' using the `.rank()` method.
4. Define a function that returns "Pass" if score >= 60 and "Fail" otherwise.
5. Apply this function to the 'Math' column to create a new 'Status' column.

# [EXERCISE] Starter Code

scores = pd.DataFrame({

    "Student": ["Alice", "Bob", "Charlie", "David"],

    "Math": [85, 45, 92, 60],

    "Science": [70, 55, 88, 72]

})



# Your code here

scores = scores.sort_values(by='Math', ascending=False)

scores['Math_Rank'] = scores['Math'].rank(ascending=False).astype(int)



def scoring(val):

    return "Pass" if val >= 60 else "Fail"



scores['Status'] = scores['Math'].apply(scoring)

scores

In [29]:
# [EXERCISE] Starter Code

'''
**Tasks:**
1. Run the starter code to generate the `scores` DataFrame.
2. Sort the DataFrame by 'Math' score in descending order (highest first).
3. Create a new column 'Math_Rank' using the `.rank()` method.
4. Define a function that returns "Pass" if score >= 60 and "Fail" otherwise.
5. Apply this function to the 'Math' column to create a new 'Status' column.
'''
scores = pd.DataFrame({
    "Student": ["Alice", "Bob", "Charlie", "David"],
    "Math": [85, 45, 92, 60],
    "Science": [70, 55, 88, 72]
})

# Your code here
scores.sort_values(by="Math", ascending=False)

scores["Math_rank"] = scores["Math"].rank(ascending = False)

def Math_Rank(val):
    return "Pass" if val > 60 else "Fail"
scores["status"] = scores["Math"].apply(Math_Rank)
scores

   Student  Math  Science  Math_rank status
0    Alice    85       70        2.0   Pass
1      Bob    45       55        4.0   Fail
2  Charlie    92       88        1.0   Pass
3    David    60       72        3.0   Fail

## 🎓 Lesson Summary

1. **Data Structures:** Series (1D) and DataFrame (2D) are the building blocks.
2. **Missing Data:** Use `isna()` and `notna()` to detect missing values.
3. **Selection:** Use `.loc[]` for labels and `.iloc[]` for positions. Use `.drop()` to remove rows/columns.
4. **Operations:** Vectorized operations are faster than loops. Use `.apply()` for custom logic.
5. **Sorting:** Organize your data to find insights quickly.

**Next Steps:** In the next lesson, we will cover Data Cleaning (handling missing values) and Aggregation (GroupBy).